### ISSUE TITLE
FR: Disable/change hotkey for selecting block

### ISSUE THREAD

**Issue by huachuman** [blorbb/obsidian-blockier#2]
I often need to select all the text in the note, but this overrides that. Is there a way around this?

**Comment by blorbb** [comment]
I was thinking about having a double hotkey ctrl-a ctrl-a to select all text. I won't be able to work on this for about a month though, so feel free to make a PR if you would like.

For now, you can do ctrl-home then ctrl-shift-end to select all.

**Comment by huachuman** [comment]
I don't really understand why the hotkey ctrl+a was chosen since it's such a fundamental one... it doesn't make much sense to override such an important hotkey lol. 

I think I'll just be removing this extension.

**Comment by blorbb** [comment]
I almost never need to select an entire note, and ctrl-a for selecting a whole block makes sense to me. It's also what Notion uses, which is what I based some of the features here from. What do you select an entire note for?

**Comment by huachuman** [comment]
In three decades of using a computer I never thought I'd encounter someone asking the question of what the purpose of ctrl/cmd a is. Never mind. I'll just mod the plugin myself.

**Comment by Mara-Li** [comment]
Overridding a pretty important key like this is a big bad idea imo..…

**Comment by blorbb** [comment]
I never really need to select an entire note so I thought overriding ctrl-a was fine, I guess others use it though :)

Thanks for the PR @Lisandra-dev !! I'll take a look at it soon

Probably won't be able to test it for a while though. @huachuman and whoever else that may stumble on this comment: if you want, you can go back to release 1.0.0, which had select block as a command, and you can set your own hotkey there. I was told to change it from a command to an editor extension (which is harder to change hotkeys for) before this plugin got merged, because it causes problems with trying to select all in contexts other than a note.
